Here is the regular Expression

<!-- AUTOGENERATED FOOTER START -->[a-zA-Z0-9 --><>\n:.,;!"§$%&/()=?]*<!-- AUTOGENERATED FOOTER STOP -->

Startstring = 
Stopstring = 
Replacementfile = 

fire here is the action

find ./ -name \*.html -exec sed -i "s/cybernetnews/cybernet/g" {} \;
